---
title: "Assignment 14, Exercise 2"
subtitle: "From Assignment 4"
author: "Anthony Cunningham"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
  html_document:
    df_print: paged
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# Change working dir in RMarkdown cell
knitr::opts_knit$set(root.dir = 
'C:/Users/AC069015/kumc_applied_stats/data_824_data_viz_and_acquisition/3_univariate_eda'
)

library(dplyr)
library(tidyr)
library(ggplot2)
library(plotly)
library(patchwork)
library(hexbin)
library(flexdashboard)

df <- mpg
```

```{r}
df[sapply(df, is.character)] <- lapply(df[sapply(df, is.character)], as.factor)
```

Vehicle Miles per Gallon (MPG)
=======================================================================

Column {data-width=500}
-----------------------------------------------------------------------

```{r}
scat <- df %>% 
  ggplot(aes(x = cty, y = hwy)) +
  geom_point(
     color = "black",
     fill = "white",
     alpha = 0.3,
     size = 1.5,
     stroke = 1.5,
     ) +
  stat_smooth(method = "lm", formula = y ~ x, se = T, level = 0.95) +
  xlab("City MPG") +
  ylab("Highway MPG") +
  # ggtitle("Vehicle Miles per Gallon (MPG)") +
  theme(
      axis.text = element_text(size = 16),
      axis.title = element_text(size = 20),
      plot.title = element_text(size = 25, face = "bold"),
      panel.border = element_rect(color = "black", fill = NA, size = 1.5)
      )
ggplotly(scat)
```

Column {data-width=500}
-----------------------------------------------------------------------

```{r}
min_cty <- min(df$cty)
max_cty <- max(df$cty)
min_hwy <- min(df$hwy)
max_hwy <- max(df$hwy)

bin <- df %>% 
  ggplot(aes(x = cty, y = hwy)) +
  geom_bin2d(binwidth = c(1,1)) +
  geom_rug(position = "jitter", sides = "tr", alpha = 0.3) +
  scale_fill_viridis_c() +
  scale_x_continuous(breaks = seq(min_cty, max_cty, 5)) +
  scale_y_continuous(breaks = seq(min_hwy, max_hwy, 5)) +
  xlab("City MPG") +
  ylab("Highway MPG") +
  # ggtitle("Vehicle Miles per Gallon (MPG)") +
  theme(
      axis.text = element_text(size = 12),
      axis.title = element_text(size = 16),
      plot.title = element_text(size = 16, face = "bold"),
      panel.border = element_rect(color = "black", fill = NA, size = 1.5)
      )
ggplotly(bin)
```

Highway MPG vs Other Factors
=======================================================================

Column {data-width=250}
-----------------------------------------------------------------------

```{r}
box <- df %>% 
  ggplot(aes(x = manufacturer, y = hwy)) +
  geom_boxplot(outlier.colour = "red") +
  geom_jitter(alpha = 1/5) +
  scale_y_continuous(breaks = seq(min_hwy, max_hwy, 5)) +
  coord_flip() +
  xlab("Manufacturer") +
  ylab("Highway Miles per Gallon") +
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(size = 12),
        panel.border = element_rect(color = "black", fill = NA, size = 1.2))
ggplotly(box)
```

Column {data-width=250}
-----------------------------------------------------------------------

```{r}
hex <- df %>% 
  ggplot(aes(x = displ, y = hwy)) +
  geom_hex(binwidth = c(0.25,1)) +
  scale_x_continuous(breaks = seq(floor(min(df$displ)), ceiling(max(df$displ)), 1)) +
  scale_y_continuous(breaks = seq(min_hwy, max_hwy, 5)) +
  scale_fill_viridis_c(option = "inferno") +
  xlab("Engine Displacement") +
  ylab("Highway Miles per Gallon") +
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(size = 12),
        panel.border = element_rect(color = "black", fill = NA, size = 1.2)
        )
ggplotly(hex)
```

Column {data-width=250}
-----------------------------------------------------------------------

```{r}
viol <- df %>% 
  ggplot(aes(y = hwy, x = class)) +
  geom_violin(
      scale = "area",
      fill = "darkgoldenrod1",
      color = "black",
      draw_quantiles = c(.25, .5, .75)
      ) +
  geom_jitter(alpha = 1/5) +
  scale_y_continuous(breaks = seq(min_hwy, max_hwy, 5)) +
  xlab("Vehicle Type") +
  ylab("Highway Miles per Gallon") +
  coord_flip() +
  theme(axis.text = element_text(10),
        axis.title = element_text(size = 12),
        panel.border = element_rect(color = "black", fill = NA, size = 1.2),
        )
ggplotly(viol)
```
